import { ApiProperty } from "@nestjs/swagger";
import { IsString, MinLength } from "class-validator";

export class ResetPasswordDto {
  @ApiProperty({ description: "Password reset token generated by forgot-password endpoint." })
  @IsString()
  @MinLength(10)
  token!: string;

  @ApiProperty({ example: "newSecurePass123" })
  @IsString()
  @MinLength(8)
  newPassword!: string;
}

